---
- name: Set state and enabled status for Podman service.
  ansible.builtin.service:
    name: podman
    state: "{{ podman_service_state }}"
    enabled: "{{ podman_service_enabled }}"
  changed_when: false
